# Copyright 2026 Yeongu Choe
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

cmake_minimum_required(VERSION 3.3)

set(CMAKE_C_COMPILER "clang")
set(CMAKE_CXX_COMPILER "clang++")

project(gpunative)

if(NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)
    set(CMAKE_BUILD_TYPE Release CACHE STRING "Build type" FORCE)
endif()

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

set(LLVM_VERSION 23.1.0)
set(LLVM_SHA256 ab1f0e3ec52448c33e8782eaf0422504b87c7b016b22514653ee0d8fcee479ff)

set(MLIR_ENABLE_BINDINGS_PYTHON ON CACHE BOOL "" FORCE)
set(LLVM_ENABLE_PROJECTS mlir CACHE STRING "" FORCE)
set(LLVM_TARGETS_TO_BUILD Native CACHE STRING "" FORCE)
set(LLVM_ENABLE_ASSERTIONS OFF CACHE BOOL "" FORCE)
set(LLVM_ENABLE_WARNINGS OFF CACHE BOOL "" FORCE)
set(LLVM_BUILD_TOOLS OFF CACHE BOOL "" FORCE)
set(LLVM_BUILD_RUNTIMES OFF CACHE BOOL "" FORCE)
set(LLVM_INCLUDE_TESTS OFF CACHE BOOL "" FORCE)
set(LLVM_INCLUDE_EXAMPLES OFF CACHE BOOL "" FORCE)
set(LLVM_INCLUDE_BENCHMARKS OFF CACHE BOOL "" FORCE)
set(LLVM_INCLUDE_DOCS OFF CACHE BOOL "" FORCE)
set(LLVM_INCLUDE_UTILS OFF CACHE BOOL "" FORCE)
set(LLVM_INCLUDE_RUNTIMES OFF CACHE BOOL "" FORCE)
set(LLVM_ENABLE_BINDINGS OFF CACHE BOOL "" FORCE)
set(LLVM_ENABLE_LIBXML2 OFF CACHE BOOL "" FORCE)
set(LLVM_ENABLE_ZSTD OFF CACHE STRING "" FORCE)
set(LLVM_ENABLE_ZLIB OFF CACHE STRING "" FORCE)
set(LLVM_ENABLE_LIBEDIT OFF CACHE BOOL "" FORCE)
set(LLVM_ENABLE_TERMINFO OFF CACHE BOOL "" FORCE)
set(LLVM_ENABLE_Z3_SOLVER OFF CACHE BOOL "" FORCE)
set(LLVM_ENABLE_LIBPFM OFF CACHE BOOL "" FORCE)
set(LLVM_APPEND_VC_REV OFF CACHE BOOL "" FORCE)
set(LLVM_ENABLE_BACKTRACES OFF CACHE BOOL "" FORCE)
set(LLVM_ENABLE_CRASH_OVERRIDES OFF CACHE BOOL "" FORCE)

include(FetchContent)
FetchContent_Declare(
    llvm
    URL https://github.com/llvm/llvm-project/releases/download/llvmorg-${LLVM_VERSION}/llvm-project-${LLVM_VERSION}.src.tar.xz
    URL_HASH SHA256=${LLVM_SHA256}
    DOWNLOAD_EXTRACT_TIMESTAMP TRUE
    SOURCE_SUBDIR llvm
    EXCLUDE_FROM_ALL
    SYSTEM
)
FetchContent_MakeAvailable(llvm)

add_library(gpunative INTERFACE)

target_include_directories(gpunative SYSTEM INTERFACE
    ${llvm_SOURCE_DIR}/llvm/include
    ${llvm_BINARY_DIR}/include
    ${llvm_SOURCE_DIR}/mlir/include
    ${llvm_BINARY_DIR}/tools/mlir/include
)

target_link_libraries(gpunative INTERFACE
    MLIRIR
    MLIRParser
    MLIRFuncDialect
    MLIRArithDialect
)

enable_testing()
add_subdirectory(test)
